export let ApiEndPoints = {
  Login: 'account/login',
  Category: 'Category',
  UserAccount: 'UserAccount/Login',
  UserRegister: 'UserAccount',
  ForgetPassword: 'UserAccount/Send-Email',
  ResetPassword: 'UserAccount/Reset',
  Sectors: 'Sectors',
  City: 'City',
  Countries: 'Countries',
  Candidate: 'Candidate',
  Department: 'Department',
  Menu: 'Menu',
  Role: 'Role',
  Job: 'Job',
  EmploymentType: 'EmploymentType',
  Employee: 'Employees',
  EmployeeTask: 'EmployeeTask',
  EmployeeTaskHour: 'EmployeeTaskHours',
  EmployeeTaskNote: 'EmployeeTaskNotes',
  TaskType: 'TaskTypes',
  TaskStatus: 'TaskStatus',
  SalaryRanges: 'SalaryRange',
  JobStatus: 'JobStatus',
  Nationality: 'Nationality',
  JobRegion: 'Region',
  Skills: 'Skill',
  UserInfo: 'UserInformations',
  CheckInOut: "CheckInOut",
  JobCandidate: 'JobCandidate',
  Skill: "Skill",
  QuestionBank: "QuestionBank"

}
